# Generated by Django 4.0.5 on 2022-07-06 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color_of_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.color_instance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
