# Generated by Django 4.0.5 on 2022-07-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='adidas', max_length=100),
            preserve_default=False,
        ),
    ]
