# Generated by Django 4.0.5 on 2023-04-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_color_of_items_orderitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='main_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='main_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
