# Generated by Django 4.0.5 on 2022-07-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('XL', 'XL'), ('XXL', 'XXL'), ('L', 'L'), ('S', 'S')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
