# Generated by Django 4.0.5 on 2022-07-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_orderitem_size_order_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
    ]
