# Generated by Django 4.0.5 on 2022-07-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
    ]
